### ISSUE TITLE
Adafruit Huzzah ESP8266 Issue with NeoPixel

### ISSUE THREAD

**Issue by ahbitrary** [arturo182/keyboard_featherwing_sw#2]
Tried using an Adafruit HUZZAH ESP8266 with the keyboard, however, I can't get the NeoPixel to play nice with the other components. 

Using the Arduino FeatherWing example, if I initialise NeoPixel, `Adafruit_NeoPixel pixels(1, NEOPIXEL_PIN, NEO_GRB + NEO_KHZ800);`, board hangs and watchdog kicks in shortly after calling `tft.begin();`.
If I don't, everything else (keyboard, TFT, and touch screen) works fine, but the NeoPixel lights up and changes colour with each button I press on the keyboard.

Wondering, if I'm doing something wrong or if it's an SPI issue with the ESP8266.

And just in case anybody wants to try to replicate the issue, I used the following the following defines for the pinouts of the ESP 8266
```
#define STMPE_CS 16
#define TFT_CS 0
#define TFT_DC 15
#define SD_CS 2
#define NEOPIXEL_PIN 13
```

**Comment by arturo182** [comment]
Hmm, I haven't tried the Huzzah ESP8266 but I can't see why the FeatherWing Neopixel would be any different from other Neopixels. I'd assume this is a SW issue or specifically ESP8266-related since other Feathers have no problems driving the Neopixel. I'd recommend trying to ask on the Adafruit Discord: https://adafru.it/discord

**Comment by ahbitrary** [comment]
Thanks for responding. I'll investigate a bit more first and ask on Discord. I'll update here if I find out the cause.

**Comment by dglaude** [comment]
Can you share your code somewhere? My Huzzah cannot run CircuitPython, so I would love to find some use for it.

I can see an interesting use with the ESP8266 running deauther but with a UI fully with the keyboard and screen.

**Comment by ahbitrary** [comment]
I don't have any original code right now. I'm still trying to make the example code work.

Individually running each peripheral works with the Huzzah. So it might just be a software issue as arturo guessed. Permutating through the combinations, it seems the NeoPixel just refuses to play nice with the tft library. 

I went digging into the library sources for the touchscreen (Adafruit_STMPE610) and the lcd driver (Adafruit_ILI9341) and found that there may be SPI issues with ESP chips in general, but that doesn't explain why driving the NeoPixel on another pin interferes with the SPI.

**Comment by ahbitrary** [comment]
Seems like the Huzzah 8266 has a pretty strict watchdog timer.

Seems like `ts.bufferEmpty()` is taking too long and that causes the watchdog to kick in. Adding a couple of `yield()` into `loop()` stopped the crashes. 
```
void loop()
{
  // Paint touch
  if (!ts.bufferEmpty()) {
    yield(); // Here
    TS_Point p = ts.getPoint();
    p.x = map(p.x, TS_MINY, TS_MAXY, tft.height(), 0);
    p.y = map(p.y, TS_MINX, TS_MAXX, 0, tft.width());
    
    pixels.setPixelColor(0, pixels.Color(255, 0, 255));
    pixels.show(); 
    
    tft.fillCircle(p.y, p.x, 3, ILI9341_MAGENTA);
    
    pixels.clear();
    pixels.show(); 
  }
  yield(); // and Here
  // Print keys to screen
  if (keyboard.keyCount()) {
    BBQ10Keyboard::KeyEvent key = keyboard.keyEvent();
    if (key.state == BBQ10Keyboard::StateRelease) {
      pixels.setPixelColor(0, pixels.Color(0, 255, 0));
      pixels.show(); 
    
      tft.print(key.key);
      
      pixels.clear();
      pixels.show(); 
    }
  }
}
```
The other change I had to make was to shift `tft.begin()` in `setup()` till after `keyboard.setBacklight(0.5f)` 
```
void setup()
{
  Wire.begin();
  const bool sd = SD.begin(SD_CS);
  //tft.begin(); << move this
  ts.begin();
  
  pixels.begin();
  pixels.setBrightness(30);
  
  keyboard.begin();
  keyboard.setBacklight(0.5f);
  
  tft.begin(); // << here instead
  tft.setRotation(1);
  ...
}
```
So this makes the example code kind of work, but the NeoPixel will still light up randomly with different colours with different button presses on the keyboard or pressing on the touch screen.

**Comment by ahbitrary** [comment]
Should have checked this at the start. 
Unfortunately, the pin chosen for NeoPixel will not work on the HUZZAH 8266 if SPI is used - the same pin is used for MOSI.
[Adafruit HUZZAH ESP8266 Pinout](https://cdn-learn.adafruit.com/assets/assets/000/046/249/original/adafruit_products_Huzzah_ESP8266_Pinout_v1.2-1.png)

Looks like I need to do some rewiring and it should work out.

**Comment by arturo182** [comment]
Thanks for the info, glad you figured it out :)
