### ISSUE TITLE
Guru Meditation Error when running arduino example code on Featherwing Huzzah32

### ISSUE THREAD

**Issue by verticalgrain** [arturo182/keyboard_featherwing_sw#3]
Hi there, 

First of all, thanks for the great product! Loving my keyboard featherwing. 

Today I connected a Featherwing Huzzah32 and tried both the arduino examples (Hello_featherwing and touchpaint). 

On both, I'm getting a Guru Meditation Error as per the screenshot below. 

Any ideas?

![Screen Shot 2020-09-22 at 7 23 04 PM](https://user-images.githubusercontent.com/1964834/93957584-6f2d6380-fd09-11ea-98e2-5d7b9324cdeb.png)

**Comment by arturo182** [comment]
Hi Jamie, see this comment for a possible solution: https://github.com/arturo182/keyboard_featherwing_sw/issues/2#issuecomment-688393280

**Comment by skieast** [comment]
I am using the SDFAT-Beta library so might not be exactly the same but here is my code snippet

```
#ifdef  ARDUINO_FEATHER_ESP32
  #define STMPE_CS 32
  #define TFT_CS 15
  #define TFT_DC 33
  #define SD_CS 14
  #define NEOPIXEL_PIN 27
  #define SD_CONFIG SdSpiConfig(SD_CS, SHARED_SPI, SD_SCK_MHZ(10))
#endif
```

And 
```
  if (!sd.begin(SD_CONFIG)) {
    tft.print("SD init error");
    sd.initErrorHalt();
  }
```

**Comment by verticalgrain** [comment]
I found the solution to this issue and have working code now. 

The issue turned out to be caused by Adafruit_STMPE610 . I removed that include, the variables like #define TS_MINX 150, and the Paint Touch code from the arduino hello_featherwing example, and the example works now on the huzzah32.

**Comment by verticalgrain** [comment]
@skieast, thank you for the code, using your code made the screen and neopixel work for me.

**Comment by skieast** [comment]
Glad it worked for you.
